FROM ubuntu:20.04

RUN apt-get update \
&& apt-get install -y python3 python3-pip python3-dev git libssl-dev libffi-dev build-essential

COPY ./sneakymailer/. /root/sneakymailer/
COPY ./sneakymailer/.pypirc  /root/.pypirc
RUN pip3 install -r /root/sneakymailer/requirements.txt
